name: 'Hello World'
description: 'Greet someone and record the time'
inputs:
  spec-path:  # id of input
    description: 'path to spec root folder'
    required: true
outputs:
  time: # id of output
    description: 'The time we greeted you'
runs:
    using: 'node12'
    main: '../write.js'