on: [push]

jobs:
  generate_api_docs:
    runs-on: ubuntu-latest
    name: Generate api docs
    steps:
      # To use this repository's private action,
      # you must check out the repository
      - name: Checkout
        uses: actions/checkout@v2
      - name: Generate spec and doc files
        uses: ./github_actions/generate_docs_action # Uses an action in the root directory
        id: generate
        with:
          spec-path: './specifications'
          output-path: './output'
      - name: Build documentation
        uses: ./github_actions/generate_slate_docs_action
        with:
          input-path: './source'
          output-path: './output/slate'
      - uses: actions/upload-artifact@v2
        with:
          name: spec-output
          path: ./output/